using System.Text.Json.Serialization;

namespace SafePatch.Protocol;

/// <summary>
/// Every message exchanged between host and worker. The session is:
/// <c>Hello → Start → (AssetRequest → AssetReply)* → Submit | Failed → Result</c>. All reads
/// happen inside the worker, through the files the host shares in <see cref="Start"/> and, for
/// loose assets, one at a time in <see cref="AssetReply"/>.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "$kind")]
[JsonDerivedType(typeof(Hello), "hello")]
[JsonDerivedType(typeof(Start), "start")]
[JsonDerivedType(typeof(AssetRequest), "assetRequest")]
[JsonDerivedType(typeof(AssetReply), "assetReply")]
[JsonDerivedType(typeof(Submit), "submit")]
[JsonDerivedType(typeof(Failed), "failed")]
[JsonDerivedType(typeof(Result), "result")]
public abstract record Message;

public static class ProtocolVersion
{
    public const int Current = 3;
}

/// <summary>Worker → host. First message; echoes the per-run nonce the host gave the worker at launch.</summary>
public sealed record Hello(int ProtocolVersion, string Nonce) : Message;

/// <summary>
/// Host → worker. The compiled program, the Synthesis arguments to run it with, and every file the
/// run may read. Paths are the host's paths; the worker serves them from memory or shared handles.
/// </summary>
/// <param name="SettingsPath">When the program has autogenerated settings: their file name under the
/// patcher's extra data folder, as passed to <c>SetAutogeneratedSettings</c>.</param>
/// <param name="GameIniPath">The game INI (one of <paramref name="Files"/>) whose archive lists the program's
/// asset provider reads. The worker cannot find it itself: My Documents does not resolve inside the sandbox.</param>
public sealed record Start(byte[] Program, IReadOnlyList<string> Arguments, IReadOnlyList<SharedFile> Files, string? SettingsPath = null, string? GameIniPath = null) : Message;

/// <summary>
/// A file visible to the worker: either small <see cref="Contents"/>, or a read-only
/// <see cref="Handle"/> the host duplicated into the worker process.
/// </summary>
public sealed record SharedFile(string Path, long? Handle = null, byte[]? Contents = null);

/// <summary>
/// Worker → host. Asks for a loose file in the Data folder, by its Data-relative path, when the
/// program reads an asset (e.g. through <c>state.AssetProvider</c>).
/// </summary>
public sealed record AssetRequest(string Path) : Message;

/// <summary>
/// Host → worker. A read-only handle to the requested file, or null when it does not exist or the
/// manifest does not allow reading it (the worker cannot tell which).
/// </summary>
public sealed record AssetReply(long? Handle) : Message;

/// <summary>Worker → host. The output plugin Synthesis wrote, and what the program printed.</summary>
/// <param name="OutputPlugins">The plugin, then its <c>_2</c>, <c>_3</c>... parts when Synthesis split it
/// because it needs more masters than one plugin can have (<c>--SplitIfMaxMastersExceeded</c>).</param>
/// <param name="Persistence">This patcher's FormKey allocation file after the run (Synthesis's
/// <c>TextFileSharedFormKeyAllocator</c>), when the run uses persistence.</param>
public sealed record Submit(IReadOnlyList<byte[]> OutputPlugins, string Log, byte[]? Persistence = null) : Message;

/// <summary>Worker → host. The run failed before producing output.</summary>
public sealed record Failed(string Error, string Log) : Message;

/// <summary>Host → worker. Final message.</summary>
public sealed record Result(bool Accepted, IReadOnlyList<string> Errors) : Message;
