using SafePatch.TestSupport;

namespace SafePatch.Worker.Core.Tests;

public class ProgramLoadingTests
{
    private const string Usings = """
        using System.Threading.Tasks;
        using Mutagen.Bethesda.Skyrim;
        using Mutagen.Bethesda.Synthesis;
        """;

    [Fact]
    public void Finds_the_native_patch_function()
    {
        var patch = PatchProgram.Load(TestPrograms.Compile(SamplePrograms.LeveledListMerge));
        Assert.NotNull(patch);
    }

    [Fact]
    public void Finds_the_field_that_receives_autogenerated_settings()
    {
        var program = PatchProgram.Load(TestPrograms.Compile(SamplePrograms.NamedList, settingsSource: SamplePrograms.NamingSettings));

        Assert.Equal("Settings", program.SettingsField?.Name);
        Assert.Null(PatchProgram.Load(TestPrograms.Compile(SamplePrograms.LeveledListMerge)).SettingsField);
    }

    [Fact]
    public void Accepts_an_async_patch_function() =>
        Assert.NotNull(PatchProgram.Load(TestPrograms.Compile(Usings + """
            public static class P { public static Task RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state) => Task.CompletedTask; }
            """)));

    [Theory]
    [InlineData("public static class P { }")]
    [InlineData("public static class P { public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> s) { } } public static class Q { public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> s) { } }")]
    [InlineData("public static class P { public static int RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> s) => 0; }")]
    [InlineData("public static class P { public static void RunPatch(ISkyrimModGetter s) { } }")]
    [InlineData("public class P { public void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> s) { } }")]
    [InlineData("internal static class P { public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> s) { } }")]
    public void Rejects_programs_without_exactly_one_patch_function(string source) =>
        Assert.Throws<InvalidOperationException>(() => PatchProgram.Load(TestPrograms.Compile(Usings + source)));

    [Fact]
    public void Rejects_bytes_that_are_not_an_assembly() =>
        Assert.ThrowsAny<BadImageFormatException>(() => PatchProgram.Load([1, 2, 3]));
}
