using System.Text.Json;
using SafePatch.Protocol;

namespace SafePatch.Host;

/// <summary>
/// Package metadata describing the program and the authority it requests. Untrusted: it can
/// only narrow the publisher's <see cref="PatchPolicy"/>.
/// </summary>
/// <param name="Writable">Fields the patch may change on overrides, as <c>Type.Field</c>, <c>Type.*</c> or <c>*</c>,
/// using Mutagen's record class and property names (e.g. <c>LeveledItem.Entries</c>).</param>
/// <param name="Creatable">Record types the patch may create, e.g. <c>LeveledItem</c>, or <c>*</c>.</param>
/// <param name="MaxRecords">Most records the patch may add or change.</param>
/// <param name="Settings">The program's autogenerated settings, when it has any.</param>
/// <param name="Assets">Loose Data files the program may read, as Data-relative glob patterns
/// (e.g. <c>meshes/**/*.nif</c>). Empty or absent: none.</param>
/// <param name="Removable">Record types the patch may remove from the patch mod (reverting an earlier patcher's
/// override, or deleting a record it added), e.g. <c>PlacedObject</c>, or <c>*</c>. Empty or absent: none.</param>
public sealed record Manifest(
    int SchemaVersion,
    string Name,
    string ProgramSha256,
    IReadOnlyList<string> Writable,
    IReadOnlyList<string> Creatable,
    int MaxRecords,
    ManifestSettings? Settings = null,
    IReadOnlyList<string>? Assets = null,
    IReadOnlyList<string>? Removable = null)
{
    public const int CurrentSchemaVersion = 3;

    public static Manifest Parse(string json)
    {
        Manifest manifest;
        try
        {
            manifest = JsonSerializer.Deserialize<Manifest>(json, FrameChannel.JsonOptions)
                       ?? throw new SafePatchException("Manifest is empty.");
        }
        catch (JsonException e)
        {
            throw new SafePatchException($"Manifest is malformed: {e.Message}", e);
        }
        manifest.Validate();
        return manifest;
    }

    public string ToJson() => JsonSerializer.Serialize(this, FrameChannel.JsonOptions);

    private void Validate()
    {
        // A package pins the runtime it was generated for, so a mismatch means a hand-edited or mixed-up package (ADR 007).
        if (SchemaVersion != CurrentSchemaVersion)
            throw new SafePatchException(
                $"Manifest schema {SchemaVersion} is not supported: this SafePatch runtime reads schema {CurrentSchemaVersion}. " +
                "Regenerate the patcher with the SafePatch version it references.");
        if (string.IsNullOrWhiteSpace(Name)) throw new SafePatchException("Manifest name is required.");
        if (ProgramSha256.Length != 64 || !ProgramSha256.All(char.IsAsciiHexDigitLower))
            throw new SafePatchException("Manifest programSha256 must be 64 lowercase hex digits.");
        if (MaxRecords < 0) throw new SafePatchException("Manifest maxRecords must not be negative.");
        foreach (var pattern in Writable) FieldPattern.Parse(pattern);
        foreach (var type in Creatable) FieldPattern.ParseType(type);
        foreach (var type in Removable ?? []) FieldPattern.ParseType(type);
        Settings?.Validate();
        foreach (var pattern in Assets ?? []) AssetPattern.Parse(pattern);
    }
}

/// <summary>
/// The settings class Synthesis shows in its settings GUI (<c>SetAutogeneratedSettings</c>), and the
/// file under the patcher's extra data folder that holds the user's values.
/// </summary>
/// <param name="Type">Full name of the settings class, e.g. <c>MyPatch.Settings</c>.</param>
/// <param name="Path">A plain file name, e.g. <c>settings.json</c>.</param>
public sealed record ManifestSettings(string Type, string Path)
{
    internal void Validate()
    {
        if (!Type.Split('.').All(IsIdentifier)) throw new SafePatchException($"Settings type '{Type}' is not a type name.");
        if (Path.Length is 0 or > 64 || !Path.EndsWith(".json", StringComparison.Ordinal) || Path.StartsWith('.')
            || !Path.All(c => char.IsAsciiLetterOrDigit(c) || c is '_' or '-' or '.'))
            throw new SafePatchException($"Settings path '{Path}' must be a plain .json file name.");
    }

    private static bool IsIdentifier(string s) =>
        s.Length is > 0 and <= 100 && (char.IsAsciiLetter(s[0]) || s[0] == '_') && s.All(c => char.IsAsciiLetterOrDigit(c) || c == '_');
}

/// <summary>Limits enforced by the trusted host. The publisher sets the maximum; a manifest may narrow it.</summary>
public sealed record PatchPolicy
{
    public required IReadOnlyList<FieldPattern> Writable { get; init; }
    public required IReadOnlyList<string> Creatable { get; init; }

    /// <summary>Record types the patch may remove from the patch mod. None unless granted.</summary>
    public IReadOnlyList<string> Removable { get; init; } = [];
    public int MaxRecords { get; init; } = 100_000;
    public int MaxProgramBytes { get; init; } = 8 * 1024 * 1024;
    public int MaxInlineFileBytes { get; init; } = 16 * 1024 * 1024;
    public int MaxLogChars { get; init; } = 200_000;

    /// <summary>Loose Data files the program may read. The publisher default allows any.</summary>
    public IReadOnlyList<AssetPattern> Assets { get; init; } = [];
    public int MaxAssetRequests { get; init; } = 100_000;
    public long MaxAssetBytes { get; init; } = 4L * 1024 * 1024 * 1024;
    public TimeSpan Timeout { get; init; } = TimeSpan.FromMinutes(10);

    /// <summary>The publisher's ceiling for this release: anything, within the numeric limits.</summary>
    public static PatchPolicy PublisherDefault { get; } = new()
    {
        Writable = [FieldPattern.Parse("*")],
        Creatable = ["*"],
        Removable = ["*"],
        Assets = [AssetPattern.Parse("**")],
    };

    public bool CanWrite(string recordType, string field) => Writable.Any(p => p.Matches(recordType, field));
    public bool CanCreate(string recordType) => Creatable.Any(t => t == "*" || t == recordType);
    public bool CanRemove(string recordType) => Removable.Any(t => t == "*" || t == recordType);
    public bool CanRead(string dataRelativePath) => Assets.Any(p => p.Matches(dataRelativePath));

    /// <summary>Applies the manifest's narrower requests. Requesting more than the policy allows is an error.</summary>
    public PatchPolicy NarrowTo(Manifest manifest)
    {
        var writable = manifest.Writable.Select(FieldPattern.Parse).ToList();
        var assets = (manifest.Assets ?? []).Select(AssetPattern.Parse).ToList();
        var removable = manifest.Removable ?? [];
        var excess = writable.Where(w => !Writable.Any(p => p.Covers(w))).Select(w => w.ToString())
            .Concat(manifest.Creatable.Where(t => !Creatable.Contains("*") && !Creatable.Contains(t)))
            .Concat(removable.Where(t => !Removable.Contains("*") && !Removable.Contains(t)))
            .Concat(assets.Where(a => !Assets.Any(p => p.Text == "**" || p.Text == a.Text)).Select(a => a.Text))
            .ToList();
        if (excess.Count > 0) throw new SafePatchException($"Manifest requests more than the policy allows: {string.Join(", ", excess)}.");
        return this with
        {
            Writable = writable, Creatable = manifest.Creatable, Removable = removable, Assets = assets, MaxRecords = Math.Min(MaxRecords, manifest.MaxRecords),
        };
    }
}

/// <summary><c>*</c>, <c>Type.*</c> or <c>Type.Field</c>.</summary>
public sealed record FieldPattern(string? Type, string? Field)
{
    public static FieldPattern Parse(string text)
    {
        if (text == "*") return new(null, null);
        var parts = text.Split('.');
        if (parts is not [var type, var field] || !IsName(type) || (field != "*" && !IsName(field)))
            throw new SafePatchException($"'{text}' is not a field pattern (Type.Field, Type.* or *).");
        return new(type, field == "*" ? null : field);
    }

    public static string ParseType(string text) =>
        text == "*" || IsName(text) ? text : throw new SafePatchException($"'{text}' is not a record type name.");

    public bool Matches(string recordType, string field) => (Type is null || Type == recordType) && (Field is null || Field == field);

    public bool Covers(FieldPattern other) =>
        (Type is null || Type == other.Type) && (Field is null || (Field == other.Field && other.Type is not null));

    public override string ToString() => Type is null ? "*" : $"{Type}.{Field ?? "*"}";

    private static bool IsName(string s) => s.Length is > 0 and <= 100 && char.IsAsciiLetter(s[0]) && s.All(char.IsAsciiLetterOrDigit);
}

public class SafePatchException(string message, Exception? inner = null) : Exception(message, inner);
