using System.Diagnostics;
using System.Xml.Linq;
using SafePatch.Host;
using SafePatch.TestSupport;

namespace SafePatch.Generator.Tests;

public sealed class PatcherGeneratorTests : IDisposable
{
    private readonly string _output = Path.Combine(Path.GetTempPath(), $"SafePatchGen-{Guid.NewGuid():N}");

    private static PatcherSpec Spec(string source = SamplePrograms.LeveledListMerge) => new()
    {
        Name = "CacoLeveledLists",
        OutputPlugin = "CacoLeveledLists.esp",
        Source = source,
        Writable = SamplePrograms.LeveledListMergeWritable,
        Runtime = new RuntimeReference.Project(Path.Combine(RepoRoot(), "src", "SafePatch.Synthesis", "SafePatch.Synthesis.csproj")),
    };

    [Fact]
    public void Writes_the_trusted_template_and_an_inert_payload()
    {
        var result = PatcherGenerator.Generate(Spec(), _output);

        Assert.True(result.Success);
        var project = Path.Combine(_output, "CacoLeveledLists");
        Assert.True(File.Exists(Path.Combine(_output, "CacoLeveledLists.sln")));
        Assert.True(File.Exists(Path.Combine(_output, "Directory.Build.props")));
        Assert.Contains("\"CacoLeveledLists.esp\"", File.ReadAllText(Path.Combine(project, "Program.cs")));

        // The payload verifies exactly as the runtime will verify it.
        var package = Preflight.Verify(
            File.ReadAllText(Path.Combine(project, "payload", "manifest.json")),
            File.ReadAllBytes(Path.Combine(project, "payload", "patch.bin")),
            PatchPolicy.PublisherDefault);
        Assert.Equal(result.ProgramSha256, package.Manifest.ProgramSha256);
        Assert.Equal(SamplePrograms.LeveledListMerge, File.ReadAllText(Path.Combine(project, "payload", "patch.safe.cs")));

        // Only Program.cs is compiled; default globbing is off, so the audit source never is.
        var csproj = XDocument.Load(Path.Combine(project, "CacoLeveledLists.csproj"));
        Assert.Equal("false", csproj.Descendants("EnableDefaultItems").Single().Value);
        Assert.Equal(["Program.cs"], csproj.Descendants("Compile").Select(c => c.Attribute("Include")!.Value));
    }

    [Fact]
    public void Compiles_settings_into_the_patcher_and_records_them_in_the_manifest()
    {
        var result = PatcherGenerator.Generate(Spec(SamplePrograms.NamedList) with { SettingsSource = SamplePrograms.NamingSettings, Writable = [] }, _output);

        Assert.True(result.Success, string.Join(Environment.NewLine, result.Diagnostics));
        var project = Path.Combine(_output, "CacoLeveledLists");
        Assert.Equal(SamplePrograms.NamingSettings, File.ReadAllText(Path.Combine(project, "Settings.cs")));
        Assert.Contains(".SetAutogeneratedSettings<global::Naming.NamingSettings>(\"CacoLeveledLists\", \"settings.json\", out _)",
            File.ReadAllText(Path.Combine(project, "Program.cs")));
        var csproj = XDocument.Load(Path.Combine(project, "CacoLeveledLists.csproj"));
        Assert.Equal(["Program.cs", "Settings.cs"], csproj.Descendants("Compile").Select(c => c.Attribute("Include")!.Value));
        var manifest = Manifest.Parse(File.ReadAllText(Path.Combine(project, "payload", "manifest.json")));
        Assert.Equal(new ManifestSettings("Naming.NamingSettings", "settings.json"), manifest.Settings);
    }

    [Fact]
    public void Describes_the_patcher_to_Synthesis_in_SynthesisMeta_json()
    {
        Assert.True(PatcherGenerator.Generate(Spec() with { Description = "Restores CACO's leveled list entries.", RequiredMods = ["Complete Alchemy & Cooking Overhaul.esp"] }, _output).Success);

        var meta = System.Text.Json.JsonDocument.Parse(File.ReadAllText(Path.Combine(_output, "CacoLeveledLists", PatcherGenerator.SynthesisMetaFile))).RootElement;
        Assert.Equal("CacoLeveledLists", meta.GetProperty("Nickname").GetString());
        Assert.Equal("Restores CACO's leveled list entries.", meta.GetProperty("OneLineDescription").GetString());
        Assert.Equal(["Complete Alchemy & Cooking Overhaul.esp"], meta.GetProperty("RequiredMods").EnumerateArray().Select(e => e.GetString()));
        Assert.Contains("SkyrimSE", meta.GetProperty("TargetedReleases").EnumerateArray().Select(e => e.GetString()));
    }

    [Fact]
    public void Records_removable_types_in_the_manifest_and_review_notes()
    {
        Assert.True(PatcherGenerator.Generate(Spec() with { Removable = ["PlacedObject"] }, _output).Success);

        var project = Path.Combine(_output, "CacoLeveledLists");
        Assert.Equal(["PlacedObject"], Manifest.Parse(File.ReadAllText(Path.Combine(project, "payload", "manifest.json"))).Removable);
        Assert.Contains("- Removable record types: `PlacedObject`", File.ReadAllText(Path.Combine(_output, "REVIEW.md")));
    }

    [Fact]
    public void Refuses_settings_with_code_and_writes_nothing()
    {
        var result = PatcherGenerator.Generate(Spec(SamplePrograms.NamedList) with
        {
            SettingsSource = SamplePrograms.NamingSettings.Replace("public int Level = 1;", "public int Level = System.Environment.ProcessorCount;"),
        }, _output);

        Assert.False(result.Success);
        Assert.Contains(result.Diagnostics, d => d.Code == "SP0305");
        Assert.False(Directory.Exists(_output));
    }

    [Fact]
    public void Refuses_a_program_that_breaks_policy_and_writes_nothing()
    {
        var result = PatcherGenerator.Generate(Spec(SamplePrograms.LeveledListMerge.Replace(
            "foreach (var winner", "var leak = System.IO.File.ReadAllText(\"x\"); foreach (var winner")), _output);

        Assert.False(result.Success);
        Assert.Contains(result.Diagnostics, d => d.Code == "SP0004");
        Assert.False(Directory.Exists(_output));
    }

    [Fact]
    public void Refuses_a_malformed_write_scope() =>
        Assert.Throws<SafePatchException>(() => PatcherGenerator.Generate(Spec() with { Writable = ["Npc Name"] }, _output));

    [Theory]
    [InlineData("Bad\" /><Target Name=\"x", "ok.esp")]
    [InlineData("../escape", "ok.esp")]
    [InlineData("Ok", "evil\"); System.IO.File.Delete(\"x.esp")]
    [InlineData("Ok", "notaplugin.txt")]
    public void Refuses_names_that_could_inject_into_the_template(string name, string plugin) =>
        Assert.Throws<ArgumentException>(() => PatcherGenerator.Generate(Spec() with { Name = name, OutputPlugin = plugin }, _output));

    [Fact]
    public void Refuses_a_non_empty_output_directory()
    {
        Directory.CreateDirectory(_output);
        File.WriteAllText(Path.Combine(_output, "existing.txt"), "");
        Assert.Throws<IOException>(() => PatcherGenerator.Generate(Spec(), _output));
    }

    [Theory]
    [Trait("Category", "Build")]
    [InlineData(false)]
    [InlineData(true)]
    public void Generated_repository_builds_with_the_worker_and_payload(bool withSettings)
    {
        PatcherGenerator.Generate(withSettings ? Spec(SamplePrograms.NamedList) with { SettingsSource = SamplePrograms.NamingSettings } : Spec(), _output);
        // The runtime project references Mutagen from the fork's local feed, which the repository's NuGet.config names.
        File.Copy(Path.Combine(RepoRoot(), "NuGet.config"), Path.Combine(_output, "NuGet.config"));

        var build = Process.Start(new ProcessStartInfo("dotnet", ["build", Path.Combine(_output, "CacoLeveledLists.sln"), "-c", "Release", "-nologo", "-v", "q"])
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
        })!;
        var log = build.StandardOutput.ReadToEnd() + build.StandardError.ReadToEnd();
        build.WaitForExit();
        Assert.True(build.ExitCode == 0, log);

        var bin = Path.Combine(_output, "CacoLeveledLists", "bin", "Release", "net10.0");
        Assert.True(File.Exists(Path.Combine(bin, "CacoLeveledLists.dll")));
        Assert.True(File.Exists(Path.Combine(bin, "SafePatch.Worker", "SafePatch.Worker.exe")));
        Assert.True(File.Exists(Path.Combine(bin, "payload", "patch.bin")));
    }

    public void Dispose()
    {
        if (Directory.Exists(_output)) Directory.Delete(_output, recursive: true);
    }

    private static string RepoRoot()
    {
        for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir is not null; dir = dir.Parent)
            if (File.Exists(Path.Combine(dir.FullName, "SafeSynthesis.slnx"))) return dir.FullName;
        throw new InvalidOperationException("Repository root not found.");
    }
}
