using CommandLine;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Environments.DI;
using Mutagen.Bethesda.Inis.DI;
using Mutagen.Bethesda.Installs.DI;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Analysis;
using SafePatch.Mutagen;
using Mutagen.Bethesda.Synthesis.CLI;
using SafePatch.Host;

namespace SafePatch.Synthesis;

/// <summary>
/// Decides what the worker may read, from the exact arguments Synthesis passed this patcher.
/// The worker gets the same arguments, less the export-only ones; every path it will open is one listed here.
/// </summary>
public static class SynthesisInputs
{
    /// <summary>Data folder files Mutagen reads while building the load order: plugins and archives. Strings files are shared from Strings\.</summary>
    public static readonly IReadOnlySet<string> DataExtensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { ".esm", ".esp", ".esl", ".bsa", ".ba2" };

    /// <param name="settingsPath">The program's settings file name (from its manifest), if it has settings.</param>
    /// <param name="gameIni">The game INI listing archives; by default, where Synthesis looks for it.</param>
    /// <param name="dataFiles">The Data folder's plugins, archives and strings files, when they are not all in the
    /// folder itself (an MO2 profile outside MO2): each is shared at its path under the Data folder.</param>
    public static RunInputs Plan(IReadOnlyList<string> arguments, string? settingsPath = null, string? gameIni = null, IReadOnlyList<InputFile>? dataFiles = null)
    {
        var run = Parse(arguments);
        var workerArguments = WorkerArguments(arguments);
        var files = new List<InputFile>();

        // Synthesis reads autogenerated settings from the patcher's extra data folder, and uses the
        // defaults when the user never saved any. The worker's pipeline does the same.
        string? settingsFile = null;
        if (settingsPath is not null && run.ExtraDataFolder is { } extraData && File.Exists(Path.Combine(extraData, settingsPath)))
        {
            settingsFile = Path.Combine(extraData, settingsPath);
            files.Add(new InputFile(settingsFile, Inline: true));
        }

        // Synthesis's shared FormKey allocation state, so the worker's allocator reuses persisted FormKeys.
        if (run.PersistencePath is { } persistence && run.PatcherName is not null)
            files.AddRange(FormKeyPersistence.Files(persistence).Select(f => new InputFile(f, Inline: true)));

        // The INI names archives to load besides those named after plugins. Under MO2 this is the profile's INI.
        gameIni ??= GameIni(run);
        if (gameIni is not null && File.Exists(gameIni)) files.Add(new InputFile(gameIni, Inline: true));
        else gameIni = null;

        if (!string.IsNullOrEmpty(run.LoadOrderFilePath) && File.Exists(run.LoadOrderFilePath))
            files.Add(new InputFile(run.LoadOrderFilePath, Inline: true));
        if (run.SourcePath is { } source && File.Exists(source))
            files.AddRange(SourceFiles(source, run.SplitIfMaxMastersExceeded).Select(f => new InputFile(f)));

        // Enumerating through the host means MO2's virtual Data folder is what the worker sees.
        if (dataFiles is not null)
        {
            files.AddRange(dataFiles);
        }
        else if (Directory.Exists(run.DataFolderPath))
        {
            files.AddRange(Directory.EnumerateFiles(run.DataFolderPath)
                .Where(f => DataExtensions.Contains(Path.GetExtension(f)))
                .Select(f => new InputFile(f)));
            var strings = Path.Combine(run.DataFolderPath, "Strings");
            if (Directory.Exists(strings))
                files.AddRange(Directory.EnumerateFiles(strings).Select(f => new InputFile(f)));
        }

        // Loose assets (meshes, textures, scripts...) are too many to share up front; the host
        // serves them on request, within the manifest's asset patterns.
        return new RunInputs(workerArguments, files, settingsFile, run.DataFolderPath, gameIni);
    }

    private static string? GameIni(RunSynthesisMutagenPatcher run) => DefaultGameIni(run.GameRelease, run.DataFolderPath);

    /// <summary>Where Synthesis's state factory looks for the game INI: under My Documents for Skyrim.</summary>
    public static string? DefaultGameIni(GameRelease release, string dataFolder) =>
        new IniPathLookup(
                new GameDirectoryLookupInjection(release, new Noggog.DirectoryPath(dataFolder).Directory),
                new ProtonPrefixProvider())
            .TryGet(release)?.Path;

    /// <summary>The plugin format the host reads the worker's output with: the one this run's Synthesis uses.</summary>
    public static PluginFormat Format(RunSynthesisMutagenPatcher run, IEnumerable<ModKey> loadOrder) =>
        new(run.TargetLanguage, run.UseUtf8ForEmbeddedStrings, run.SplitIfMaxMastersExceeded, [.. loadOrder]);

    /// <summary>
    /// The worker's arguments: Synthesis's, without <c>--Localize</c>. The worker's plugin is an
    /// intermediate the host re-reads; the host's own pipeline writes (and localizes) the real output.
    /// Everything that affects reading, or the patch's starting FormIDs, is kept.
    /// </summary>
    public static IReadOnlyList<string> WorkerArguments(IReadOnlyList<string> arguments)
    {
        var worker = arguments.Where(a => !string.Equals(a, "--Localize", StringComparison.OrdinalIgnoreCase)).ToList();
        if (Parse(worker).Localize) throw new SafePatchException("Could not remove --Localize from the worker's arguments.");
        return worker;
    }

    /// <summary>
    /// The previous patcher's output, its split parts when Synthesis splits plugins (it merges them
    /// on read), and the strings files of a localized one (<c>Strings\&lt;name&gt;_&lt;language&gt;.*</c>).
    /// </summary>
    private static IEnumerable<string> SourceFiles(string source, bool split)
    {
        var modPath = new ModPath(ModKey.FromFileName(Path.GetFileName(source)), source);
        var plugins = split && MultiModFileAnalysis.GetSplitModFiles(modPath) is { Count: > 0 } parts ? parts.Select(p => p.Path).ToList() : [source];
        var strings = Path.Combine(Path.GetDirectoryName(source)!, "Strings");
        if (!Directory.Exists(strings)) return plugins;
        return plugins.Concat(Directory.EnumerateFiles(strings).Where(f =>
            plugins.Any(p => Path.GetFileName(f).StartsWith(Path.GetFileNameWithoutExtension(p) + "_", StringComparison.OrdinalIgnoreCase))));
    }

    public static RunSynthesisMutagenPatcher Parse(IReadOnlyList<string> arguments) =>
        new Parser(s => s.IgnoreUnknownArguments = true)
            .ParseArguments<RunSynthesisMutagenPatcher>(arguments)
            .MapResult(a => a, _ => throw new SafePatchException("Arguments are not a Synthesis patcher run."));
}
