using System.Reflection;
using System.Runtime.Loader;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;

namespace SafePatch.Worker.Core;

/// <summary>
/// A loaded program: its patch function — exactly one <c>public static RunPatch</c> taking
/// <c>IPatcherState&lt;ISkyrimMod, ISkyrimModGetter&gt;</c> and returning void or Task, the same
/// function a native patcher passes to <c>SynthesisPipeline.AddPatch</c> — and, when it has
/// autogenerated settings, the <c>public static Lazy&lt;TSettings&gt;</c> field a native patcher
/// passes to <c>SetAutogeneratedSettings</c>.
/// </summary>
public sealed record PatchProgram(Func<IPatcherState<ISkyrimMod, ISkyrimModGetter>, Task> Run, FieldInfo? SettingsField)
{
    public const string EntryPointName = "RunPatch";

    public static PatchProgram Load(byte[] program)
    {
        var context = new AssemblyLoadContext("SafePatch.Program");
        using var stream = new MemoryStream(program, writable: false);
        var assembly = context.LoadFromStream(stream);
        var types = assembly.GetExportedTypes();

        var candidates = types
            .SelectMany(t => t.GetMethods(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly))
            .Where(m => m.Name == EntryPointName
                        && m.GetParameters() is [var p] && p.ParameterType == typeof(IPatcherState<ISkyrimMod, ISkyrimModGetter>)
                        && (m.ReturnType == typeof(void) || m.ReturnType == typeof(Task)))
            .ToList();
        if (candidates.Count != 1)
            throw new InvalidOperationException(
                $"Program must have exactly one public static {EntryPointName}(IPatcherState<ISkyrimMod, ISkyrimModGetter>); found {candidates.Count}.");

        var method = candidates[0];
        Func<IPatcherState<ISkyrimMod, ISkyrimModGetter>, Task> run = method.ReturnType == typeof(Task)
            ? method.CreateDelegate<Func<IPatcherState<ISkyrimMod, ISkyrimModGetter>, Task>>()
            : state =>
            {
                method.CreateDelegate<Action<IPatcherState<ISkyrimMod, ISkyrimModGetter>>>()(state);
                return Task.CompletedTask;
            };

        var settings = types
            .SelectMany(t => t.GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly))
            .Where(f => f.FieldType.IsGenericType && f.FieldType.GetGenericTypeDefinition() == typeof(Lazy<>)
                        && f.FieldType.GetGenericArguments()[0].Assembly == assembly && !f.IsInitOnly)
            .ToList();
        return new PatchProgram(run, settings.Count == 1 ? settings[0] : null);
    }
}
