namespace SafePatch.TestSupport;

/// <summary>
/// A fake Mod Organizer 2 instance on disk: an ini, a profile and mod folders, but no MO2. The standard plugins
/// are spread across it: Skyrim.esm in the game's Data folder, CACO and OtherMod each in a mod. Loose files show
/// the layering. <c>textures\shared.dds</c> is in the game, both mods, a disabled mod and overwrite. Overwrite
/// wins. <c>meshes\mod.nif</c> is in both enabled mods, and OtherMod (the higher) wins.
/// </summary>
public sealed class Mo2Fixture
{
    public const string Profile = "Testing";
    public const string CacoMod = "CACO";
    public const string OtherMod = "Other Mod";
    public const string DisabledMod = "Disabled Mod";
    public const string SharedTexture = @"textures\shared.dds";
    public const string ModMesh = @"meshes\mod.nif";

    public required string Instance { get; init; }
    public required string GameFolder { get; init; }
    public required PluginFixture Plugins { get; init; }

    public string DataFolder => Path.Combine(GameFolder, "Data");
    public string ProfileFolder => Path.Combine(Instance, "profiles", Profile);
    public string ModFolder(string mod) => Path.Combine(Instance, "mods", mod);
    public string Overwrite => Path.Combine(Instance, "overwrite");

    /// <summary>A portable instance at <paramref name="root"/>\MO2 managing a game at <paramref name="root"/>\Game.</summary>
    public static Mo2Fixture Write(string root)
    {
        var instance = Path.Combine(root, "MO2");
        var game = Path.Combine(root, "Game");
        var data = Path.Combine(game, "Data");
        Directory.CreateDirectory(data);
        var plugins = PluginFixture.Write(data, Path.Combine(root, "plugins-staging"));

        var fixture = new Mo2Fixture { Instance = instance, GameFolder = game, Plugins = plugins };
        MoveInto(Path.Combine(root, "plugins-staging", PluginFixture.Caco), fixture.ModFolder(CacoMod));
        MoveInto(Path.Combine(root, "plugins-staging", PluginFixture.Other), fixture.ModFolder(OtherMod));
        Directory.Delete(Path.Combine(root, "plugins-staging"));

        WriteLoose(data, SharedTexture, "game");
        WriteLoose(fixture.ModFolder(CacoMod), SharedTexture, "caco");
        WriteLoose(fixture.ModFolder(CacoMod), ModMesh, "caco");
        WriteLoose(fixture.ModFolder(OtherMod), SharedTexture, "other");
        WriteLoose(fixture.ModFolder(OtherMod), ModMesh, "other");
        WriteLoose(fixture.ModFolder(DisabledMod), SharedTexture, "disabled");
        WriteLoose(fixture.Overwrite, SharedTexture, "overwrite");
        Directory.CreateDirectory(fixture.ModFolder("Patches_separator"));

        // Qt's format, as MO2 writes it: paths in @ByteArray with escaped backslashes, folders relative to the base.
        File.WriteAllText(Path.Combine(instance, "ModOrganizer.ini"), $"""
            [General]
            gameName=Skyrim Special Edition
            gamePath=@ByteArray({game.Replace(@"\", @"\\")})
            selected_profile=@ByteArray({Profile})

            [Settings]
            mod_directory=%BASE_DIR%/mods
            """);
        Directory.CreateDirectory(fixture.ProfileFolder);
        File.WriteAllLines(Path.Combine(fixture.ProfileFolder, "modlist.txt"),
        [
            "# This file was automatically generated by Mod Organizer.",
            "+Patches_separator",
            $"+{OtherMod}",
            $"-{DisabledMod}",
            $"+{CacoMod}",
            "*DLC: Dawnguard",
        ]);
        PluginFixture.WriteLoadOrder(Path.Combine(fixture.ProfileFolder, "plugins.txt"));
        File.WriteAllText(Path.Combine(fixture.ProfileFolder, "settings.ini"), "[General]\nLocalSettings=false\n");
        return fixture;
    }

    /// <summary>The Data folder MO2 would show, copied into <paramref name="target"/>, with its own plugins.txt.</summary>
    public (string Data, string PluginsFile) Flatten(string target)
    {
        var data = Path.Combine(target, "Data");
        foreach (var layer in new[] { DataFolder, ModFolder(CacoMod), ModFolder(OtherMod), Overwrite })
        {
            foreach (var file in Directory.EnumerateFiles(layer, "*", SearchOption.AllDirectories))
            {
                var copy = Path.Combine(data, Path.GetRelativePath(layer, file));
                Directory.CreateDirectory(Path.GetDirectoryName(copy)!);
                File.Copy(file, copy, overwrite: true);
            }
        }
        return (data, PluginFixture.WriteLoadOrder(Path.Combine(target, "plugins.txt")));
    }

    private static void MoveInto(string file, string folder)
    {
        Directory.CreateDirectory(folder);
        File.Move(file, Path.Combine(folder, Path.GetFileName(file)));
    }

    private static void WriteLoose(string root, string relative, string contents)
    {
        var path = Path.Combine(root, relative);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, contents);
    }
}
