using System.Security.Cryptography;
using System.Text;
using SafePatch.TestSupport;

namespace SafePatch.Mutagen.Tests;

/// <summary>
/// Autogenerated settings reach the program the native way: Synthesis's pipeline in the worker reads
/// them from the patcher's extra data folder into the program's <c>Lazy&lt;TSettings&gt;</c>.
/// </summary>
public class SettingsTests
{
    private const string SettingsType = "Naming.NamingSettings";

    private static string WriteSettings(HostRun run, string json)
    {
        Directory.CreateDirectory(run.ExtraDataFolder);
        File.WriteAllText(Path.Combine(run.ExtraDataFolder, "settings.json"), json);
        return Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(json)));
    }

    [Fact]
    public void Without_saved_settings_the_program_sees_the_defaults()
    {
        using var run = new HostRun();

        var report = run.RunWithSettings(SamplePrograms.NamedList, SamplePrograms.NamingSettings, SettingsType, creatable: ["LeveledItem"]);

        Assert.Equal("LItemDefault", Assert.Single(report.Changes).EditorId);
        Assert.Null(report.SettingsSha256);
    }

    [Fact]
    public void Saved_settings_change_what_the_program_does()
    {
        using var run = new HostRun();
        var hash = WriteSettings(run, """{ "Mode": "Create", "EditorId": "LItemFromSettings", "Level": 3 }""");

        var report = run.RunWithSettings(SamplePrograms.NamedList, SamplePrograms.NamingSettings, SettingsType, creatable: ["LeveledItem"]);

        Assert.Equal("LItemFromSettings", Assert.Single(report.Changes).EditorId);
        Assert.Equal(hash, report.SettingsSha256);
        Assert.Equal("LItemFromSettings", Assert.Single(run.PatchMod.LeveledItems).EditorID);
    }

    [Fact]
    public void A_setting_can_turn_the_program_off()
    {
        using var run = new HostRun();
        WriteSettings(run, """{ "Mode": "Skip" }""");

        var report = run.RunWithSettings(SamplePrograms.NamedList, SamplePrograms.NamingSettings, SettingsType, creatable: ["LeveledItem"]);

        Assert.Empty(report.Changes);
    }
}
