using Microsoft.CodeAnalysis;

namespace SafePatch.Compiler;

/// <summary>
/// Types agent code may use: the Mutagen/Synthesis API (which inside the worker only reaches the
/// sandbox-local, read-only file system) plus a deliberately small set of framework types — pure
/// data structures and algorithms, no I/O, reflection, threading, time, randomness or environment.
/// </summary>
/// <remarks>
/// This is a diagnostic filter and defense in depth, not the security boundary; the OS sandbox is.
/// </remarks>
public static class ApiAllowList
{
    /// <summary>Every public type in these namespaces is allowed.</summary>
    private static readonly HashSet<string> Namespaces = new(StringComparer.Ordinal)
    {
        "System.Collections.Generic",
    };

    /// <summary>Every public type in these namespaces and their sub-namespaces is allowed.</summary>
    private static readonly string[] NamespaceRoots = ["Mutagen.Bethesda", "Noggog", "Loqui"];

    /// <summary>Individually allowed types, by metadata name.</summary>
    private static readonly HashSet<string> Types = new(StringComparer.Ordinal)
    {
        // Primitives and core value types.
        "System.Object", "System.String", "System.Boolean", "System.Char",
        "System.Byte", "System.SByte", "System.Int16", "System.UInt16", "System.Int32", "System.UInt32",
        "System.Int64", "System.UInt64", "System.Single", "System.Double", "System.Decimal",
        "System.Void", "System.Enum", "System.ValueType", "System.Nullable`1", "System.Index", "System.Range",
        "System.Math", "System.MathF", "System.HashCode", "System.Array",
        "System.StringComparison", "System.StringComparer", "System.StringSplitOptions", "System.MidpointRounding",
        "System.IComparable`1", "System.IEquatable`1", "System.IComparable",
        "System.FormattableString", "System.IFormatProvider",
        "System.Tuple", "System.Tuple`1", "System.Tuple`2", "System.Tuple`3", "System.Tuple`4",
        "System.ValueTuple", "System.ValueTuple`1", "System.ValueTuple`2", "System.ValueTuple`3", "System.ValueTuple`4",
        "System.ValueTuple`5", "System.ValueTuple`6", "System.ValueTuple`7",

        // Delegates for lambdas.
        "System.Action", "System.Action`1", "System.Action`2", "System.Action`3", "System.Action`4",
        "System.Func`1", "System.Func`2", "System.Func`3", "System.Func`4", "System.Func`5",
        "System.Predicate`1", "System.Comparison`1", "System.Converter`2",

        // Exceptions a program may throw or catch.
        "System.Exception", "System.InvalidOperationException", "System.ArgumentException",
        "System.ArgumentNullException", "System.ArgumentOutOfRangeException", "System.NotSupportedException",
        "System.FormatException", "System.OverflowException",

        // Collections and LINQ.
        "System.Collections.IEnumerable", "System.Collections.IEnumerator",
        "System.Linq.Enumerable", "System.Linq.IGrouping`2", "System.Linq.ILookup`2", "System.Linq.IOrderedEnumerable`1",
        "System.Text.StringBuilder",

        // Native patchers log to the console and may be async; the worker captures and bounds both.
        "System.Console", "System.Threading.Tasks.Task", "System.Threading.Tasks.Task`1", "System.Threading.CancellationToken",

        // Autogenerated settings arrive the native way, as a static Lazy<TSettings> the pipeline fills.
        "System.Lazy`1",

        // Reading streams the API hands out (state.AssetProvider). Opening paths stays denied (see IsDeniedMember).
        "System.IO.Stream", "System.IO.MemoryStream", "System.IO.SeekOrigin",
        "System.IO.TextReader", "System.IO.StreamReader", "System.IO.BinaryReader", "System.IO.EndOfStreamException",

        // Mutagen's colours (an NPC's TextureLighting, a light's Color): values only. Not SystemColors, which reads the OS's.
        "System.Drawing.Color", "System.Drawing.KnownColor",

        // Compiler-synthesized helpers (interpolated strings, collection expressions).
        "System.Runtime.CompilerServices.DefaultInterpolatedStringHandler",
        "System.Runtime.CompilerServices.CollectionBuilderAttribute",
    };

    /// <summary>Members that are denied even on an allowed type.</summary>
    private static readonly HashSet<string> DeniedMembers = new(StringComparer.Ordinal)
    {
        "System.Object.GetType",
        "System.Array.CreateInstance",
        "System.Array.CreateInstanceFromArrayType",
    };

    public static bool IsAllowedType(INamedTypeSymbol type)
    {
        var definition = type.OriginalDefinition;
        if (definition.ContainingType is { } outer) return IsAllowedType(outer);
        var ns = definition.ContainingNamespace?.ToDisplayString() ?? "";
        return Namespaces.Contains(ns)
               || NamespaceRoots.Any(root => ns == root || ns.StartsWith(root + ".", StringComparison.Ordinal))
               || Types.Contains(MetadataName(definition));
    }

    /// <summary>Allowed types whose constructors can also open a file by path; those overloads are denied.</summary>
    private static readonly HashSet<string> PathConstructorTypes = new(StringComparer.Ordinal) { "System.IO.StreamReader" };

    public static bool IsDeniedMember(ISymbol member)
    {
        var type = MetadataName(member.ContainingType.OriginalDefinition);
        if (member is IMethodSymbol { MethodKind: MethodKind.Constructor } constructor && PathConstructorTypes.Contains(type)
            && constructor.Parameters.FirstOrDefault()?.Type.SpecialType == SpecialType.System_String)
            return true;
        return DeniedMembers.Contains($"{type}.{member.Name}");
    }

    private static string MetadataName(INamedTypeSymbol type) =>
        type.ContainingNamespace is { IsGlobalNamespace: false } ns ? $"{ns.ToDisplayString()}.{type.MetadataName}" : type.MetadataName;
}
